name       : gjs
version    : 1.50.1
release    : 19
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gjs/1.50/gjs-1.50.1.tar.xz : 41519fd63978745d17dbccb688a55f1850a7ba72f3c86274ca985d88dbff9fdf
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-52)
rundeps    :
    - mozjs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
