name       : gjs
version    : 1.76.2
release    : 53
source     :
    - https://download.gnome.org/sources/gjs/1.76/gjs-1.76.2.tar.xz : f7d8c9d653ea6fd78afe4a50720e046aa2bfc078fda635dd13067dd199c625d4
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-102)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
