name       : gjs
version    : 1.52.3
release    : 26
source     :
    - https://download.gnome.org/sources/gjs/1.52/gjs-1.52.3.tar.xz : ce21d8a83f6077b011b8834c4936281be65b2b62387f0745c3eb9adf780996fc
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-52)
rundeps    :
    - mozjs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
