name       : gjs
version    : 1.52.2
release    : 25
source     :
    - https://download.gnome.org/sources/gjs/1.52/gjs-1.52.2.tar.xz : 28bd9c9afabf934f43c55d97fa693a2f207c866c70eeba089a2306d3af47a003
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-52)
rundeps    :
    - mozjs
setup      : |
    %apply_patches
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
