name       : gjs
version    : 1.74.0
release    : 51
source     :
    - https://download.gnome.org/sources/gjs/1.74/gjs-1.74.0.tar.xz : 7d6418af62cc73556ab2c25b4adf67f45238ab8925888f7a57251359d4ebed1e
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-102)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
