name       : gjs
version    : 1.63.2
release    : 31
source     :
    - https://download.gnome.org/sources/gjs/1.63/gjs-1.63.2.tar.xz : b5bd2ca9fbd311d5002f4f352981613b82b8264218ecfa047caf5a17ac79c3fd
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-60)
rundeps    :
    - mozjs
setup      : |
    %patch -p1 < $pkgfiles/build-Mark-SweepingAPI-as-a-system-header.patch
    %patch -p1 < $pkgfiles/build-Fix-installation-with-DESTDIR-set.patch
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
