name       : gjs
version    : 1.72.1
release    : 50
source     :
    - https://download.gnome.org/sources/gjs/1.72/gjs-1.72.1.tar.xz : 17c0b1ec3f096671ff8bfaba6e4bbf14198c7013c604bfd677a9858da079c0ab
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-91)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
