name       : gjs
version    : 1.64.0
release    : 33
source     :
    - https://download.gnome.org/sources/gjs/1.64/gjs-1.64.0.tar.xz : 66384cbc6b849ea67ced0ad559d589bb15b5a664bbacc75c9f128416ee8ed66f
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-68)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
