name       : gjs
version    : 1.54.3
release    : 27
source     :
    - https://download.gnome.org/sources/gjs/1.54/gjs-1.54.3.tar.xz : 76b30dcc3ce9836c053aee531aa9f1d9d3f94b8503adf0a5a7bd176c492ba6b1
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-60)
rundeps    :
    - mozjs
setup      : |
    #%patch -p1 < $pkgfiles/0001-Test-removing-spidermonkey-validation.patch
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
