name       : gjs
version    : 1.48.5
release    : 16
source     :
    - https://download.gnome.org/sources/gjs/1.48/gjs-1.48.5.tar.xz : cc37998e283b6e25e1814026aa5bb96e145e1ce902b02133977bbdac8db3e042
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-38)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
