name       : gjs
version    : 1.70.0
release    : 47
source     :
    - https://download.gnome.org/sources/gjs/1.70/gjs-1.70.0.tar.xz : 4b0629341a318a02374e113ab97f9a9f3325423269fc1e0b043a5ffb01861c5f
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-78)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
