name       : gjs
version    : 1.45.4
release    : 12
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gjs/1.45/gjs-1.45.4.tar.xz : db51bc2aae51700a2a8ca8ba597c488505d106bc70b9605e77c6ab5183212228
component  : desktop.gnome.core
homepage   : https://live.gnome.org/Gjs
license    : GPL-2.0
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-24)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
