name       : gjs
version    : 1.48.3
release    : 15
source     :
    - https://download.gnome.org/sources/gjs/1.48/gjs-1.48.3.tar.xz : 669b7d78ad98390a762eec50d7cc637e25f196d986c0200d9f1c3a0e0cd90f33
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-38)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
