name       : gjs
version    : 1.58.0
release    : 28
source     :
    - https://download.gnome.org/sources/gjs/1.58/gjs-1.58.0.tar.xz : 1ed16a09c5970064df8b6f59564d0748f81e62eb56257c8911c01ff1ece57ef3
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-60)
rundeps    :
    - mozjs
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
