name       : gjs
version    : 1.50.2
release    : 20
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gjs/1.50/gjs-1.50.2.tar.xz : 2fad902cf7a7806454121c03918755c646fcfd6b08b52d488987db4e2d691ff3
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-52)
rundeps    :
    - mozjs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
