name       : gjs
version    : 1.68.0
release    : 41
source     :
    - https://download.gnome.org/sources/gjs/1.68/gjs-1.68.0.tar.xz : f00e74a00e81ab61bb92669e0f1c8bb613cc019586097f06aed0572efcaf1aef
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-78)
rundeps    :
    - mozjs
setup      : |
    %patch -p1 < $pkgfiles/overrides-Gio-Fix_LocalFilePrototype.patch
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
