name       : gjs
version    : 1.50.4
release    : 23
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gjs/1.50/gjs-1.50.4.tar.xz : b336e8709347e3c94245f6cbc3465f9a49f3ae491a25f49f8a97268f5235b93a
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-52)
rundeps    :
    - mozjs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
