name       : gjs
version    : 1.64.4
release    : 37
source     :
    - https://download.gnome.org/sources/gjs/1.64/gjs-1.64.4.tar.xz : a3cc3a8eda87074b2c363ffe28b29a5202d7f12914b6973f199acf2d1816d44c
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mozjs-68)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
