name       : gjs
version    : 1.72.0
release    : 49
source     :
    - https://download.gnome.org/sources/gjs/1.72/gjs-1.72.0.tar.xz : 3ef0caf716e3920dd61f7748f6d56e476cc0fc18351ad0548e7df1a0ab9bdcad
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-91)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
